{"uuid": "223e0eb6-efd2-4083-88c6-a408a3ea585e", "children": ["d6d48a0f-bba5-4737-902f-f9604a1412f6"], "befores": [{"name": "_xunit_setup_method_fixture_TestMapSearch", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.SessionNotCreatedException: Message: Could not create a session: The Safari instance is already paired with another WebDriver session.\n\n", "trace": "  File \"/Users/aleksandr/Desktop/vs capital/autotestBoxBerry/lib/python3.9/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Users/aleksandr/Desktop/vs capital/autotestBoxBerry/lib/python3.9/site-packages/_pytest/fixtures.py\", line 1129, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Users/aleksandr/Desktop/vs capital/autotestBoxBerry/lib/python3.9/site-packages/_pytest/fixtures.py\", line 901, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/Users/aleksandr/Desktop/vs capital/autotestBoxBerry/lib/python3.9/site-packages/_pytest/python.py\", line 907, in xunit_setup_method_fixture\n    _call_with_optional_argument(func, method)\n  File \"/Users/aleksandr/Desktop/vs capital/autotestBoxBerry/lib/python3.9/site-packages/_pytest/python.py\", line 788, in _call_with_optional_argument\n    func()\n  File \"/Volumes/Data/Python/autotestBoxBerry/Test_map_BB.py\", line 15, in setup\n    self.safari = webdriver.Safari()\n  File \"/Users/aleksandr/Desktop/vs capital/autotestBoxBerry/lib/python3.9/site-packages/selenium/webdriver/safari/webdriver.py\", line 110, in __init__\n    super().__init__(command_executor=executor, options=options, desired_capabilities=desired_capabilities)\n  File \"/Users/aleksandr/Desktop/vs capital/autotestBoxBerry/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py\", line 286, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"/Users/aleksandr/Desktop/vs capital/autotestBoxBerry/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py\", line 378, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n  File \"/Users/aleksandr/Desktop/vs capital/autotestBoxBerry/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py\", line 440, in execute\n    self.error_handler.check_response(response)\n  File \"/Users/aleksandr/Desktop/vs capital/autotestBoxBerry/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py\", line 245, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1676965346199, "stop": 1676965348820}], "start": 1676965346199, "stop": 1676965348927}